url: 'https://ecoco.sc.github.io'
baseurl: 'ecoco-sc'

title: Ecoco
email: ecoco.sc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: '' # the subpath of your site, e.g. /blog
twitter_username: jekyllrb
github_username: jekyll

# Build settings
plugins:
    - jekyll-feed
    - jekyll-postcss

collections:
    fitxes:
        output: true
        permalink: /:collection/:title
    noticies:
        output: true
        permalink: /:collection/:title

postcss:
    cache: false
